server:
  port: 8080

spring:
  application:
    name: health

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/health_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true   # 开启下划线转驼峰（user_name -> userName）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL，方便你调试
  global-config:
    db-config:
      id-type: auto       # 主键自增
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    org.example.health.mapper: debug